pipeline {
	agent any 
	stages{
		stage('0-action0'){
			steps{
			    checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'jenkins-access', url: 'https://github.com/ArmandCantiller87/Techop-team8project.git']])
			}
		}
		stage('1-currently running processes'){
			steps{
				sh 'ps -ef'
			}
		}
		stage('2-Jenkins status'){
			steps{
				sh 'sudo systemctl status Jenkins'
			}
		}
		
	}
}